# Generated by Django 5.0.7 on 2024-07-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/thumbnails/'),
        ),
    ]
